// pg/to-db.js
import { schemaFromDb } from './from-db.js'
import { queryRows } from '../shared/sql.js'
import { defaultLiteral, quoteId, quoteLit, toFieldDef, typeSql } from './to-field.js'
import { schemaDiff } from '../../diff.js'

function tableData(tableSchema) {
    const row = tableSchema.additionalProperties ?? {}
    const fields = Object.entries(row.properties ?? {})
    const required = new Set(row.required ?? [])
    return { fields, required }
}

function primaryFields(fields) {
    return fields.filter(([, f]) => f['x-index'] === 'primary').map(([n]) => n)
}

const columnProps = new Set([
    'type', 'format', 'contentEncoding', 'maxLength', 'minLength',
    'minimum', 'maximum', 'multipleOf',
])

function hasOwn(obj, key) {
    return Object.prototype.hasOwnProperty.call(obj, key)
}

function setEqual(a, b) {
    if (a.size !== b.size) return false
    for (const v of a) if (!b.has(v)) return false
    return true
}

function fieldChanged(diffs, table, field, prop) {
    return diffs.some(d => {
        const [a, b, c, e, f] = d.path
        return a === 'properties' && b === table && c === 'additionalProperties' && e === 'properties' && f === field &&
            (columnProps.has(d.property) || d.property === 'default' && hasOwn(prop, 'default') || d.property === 'x-autoincrement')
    })
}

function preserveDefault(prop, currProp) {
    return hasOwn(prop, 'default') || !hasOwn(currProp, 'default')
        ? prop
        : { ...prop, default: currProp.default }
}

function secondaryIndexKind(table, name, prop) {
    if (prop['x-index'] === 'unique') return 'UNIQUE INDEX'
    if (prop['x-index'] === true) return 'INDEX'
    if (prop['x-index'] === 'fulltext')
        console.warn(`Skip FULLTEXT INDEX ${table}.${name}: PostgreSQL fulltext requires an expression index`)
    return null
}

function indexName(table, name) {
    return `idx_${table}_${name}`
}

function createIndex(table, name, kind) {
    return `CREATE ${kind} ${quoteId(indexName(table, name))} ON ${quoteId(table)} (${quoteId(name)});`
}

async function tableIndexes(query, table) {
    const primaryRows = await queryRows(query, `
        SELECT con.conname, array_agg(a.attname ORDER BY u.ord) AS columns
        FROM pg_constraint con
        JOIN pg_class t ON t.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        JOIN unnest(con.conkey) WITH ORDINALITY AS u(attnum, ord) ON true
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = u.attnum
        WHERE con.contype = 'p' AND n.nspname = current_schema() AND t.relname = ${quoteLit(table)}
        GROUP BY con.conname
    `)
    const secondary = await queryRows(query, `
        SELECT ci.relname AS key, a.attname AS column, i.indisunique AS unique
        FROM pg_index i
        JOIN pg_class t ON t.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        JOIN pg_class ci ON ci.oid = i.indexrelid
        JOIN unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON true
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = k.attnum
        WHERE NOT i.indisprimary
          AND array_length(i.indkey, 1) = 1
          AND n.nspname = current_schema()
          AND t.relname = ${quoteLit(table)}
    `)
    const primary = primaryRows[0]
    return { primaryName: primary?.conname, primary: primary?.columns ?? [], secondary }
}

function commentStmt(table, name, comment) {
    return `COMMENT ON COLUMN ${quoteId(table)}.${quoteId(name)} IS ${comment ? quoteLit(comment) : 'NULL'};`
}

function alterFieldStmts(table, name, prop, currProp, required, currRequired, changed) {
    const stmts = [], tableId = quoteId(table), colId = quoteId(name)
    if (currProp['x-autoincrement'] && !prop['x-autoincrement'])
        stmts.push(`ALTER TABLE ${tableId} ALTER COLUMN ${colId} DROP IDENTITY IF EXISTS;`)
    if (changed && typeSql(prop) !== typeSql(currProp))
        stmts.push(`ALTER TABLE ${tableId} ALTER COLUMN ${colId} TYPE ${typeSql(prop)} USING ${colId}::${typeSql(prop)};`)
    if (prop['x-autoincrement'] && !currProp['x-autoincrement'] && hasOwn(currProp, 'default'))
        stmts.push(`ALTER TABLE ${tableId} ALTER COLUMN ${colId} DROP DEFAULT;`)
    if (prop['x-autoincrement'] && !currProp['x-autoincrement'])
        stmts.push(`ALTER TABLE ${tableId} ALTER COLUMN ${colId} ADD GENERATED BY DEFAULT AS IDENTITY;`)
    if (hasOwn(prop, 'default') && !prop['x-autoincrement'])
        stmts.push(`ALTER TABLE ${tableId} ALTER COLUMN ${colId} SET DEFAULT ${defaultLiteral(prop)};`)
    if (required !== currRequired)
        stmts.push(`ALTER TABLE ${tableId} ALTER COLUMN ${colId} ${required ? 'SET' : 'DROP'} NOT NULL;`)
    if (prop['$comment'] !== currProp['$comment'])
        stmts.push(commentStmt(table, name, prop['$comment']))
    return stmts
}

export async function schemaToDb(schema, query, { force = false, patch = false } = {}) {
    const current = await schemaFromDb(query)
    const diffs = schemaDiff(schema, current)

    if (!patch) {
        const destructive = diffs.filter(d => d.destructive === true)
        if (destructive.length && !force) {
            const msgs = destructive.map(d => `  ${d.path.join('.')} - ${d.msg}`).join('\n')
            throw new Error(`Destructive schema changes detected (use force to apply):\n${msgs}`)
        }
    }

    const stmts = []
    const nextTables = Object.keys(schema.properties ?? {})
    const currTables = Object.keys(current.properties ?? {})

    for (const table of nextTables) {
        const tableId = quoteId(table)
        const { fields, required } = tableData(schema.properties[table])
        const primaries = primaryFields(fields)
        for (const p of primaries) required.add(p)

        if (!currTables.includes(table)) {
            const cols = fields.map(([n, f]) =>
                '  ' + toFieldDef(n, f, { required: required.has(n) })
            ).join(',\n')
            const pk = primaries.length
                ? `,\n  PRIMARY KEY (${primaries.map(quoteId).join(', ')})`
                : ''
            const primarySet = new Set(primaries)
            stmts.push(`CREATE TABLE ${tableId} (\n${cols}${pk}\n);`)
            for (const [n, f] of fields) if (f['$comment']) stmts.push(commentStmt(table, n, f['$comment']))
            for (const [n, f] of fields) {
                if (primarySet.has(n)) continue
                const kind = secondaryIndexKind(table, n, f)
                if (kind) stmts.push(createIndex(table, n, kind))
            }
        } else {
            const { fields: currFieldEntries, required: currRequired } = tableData(current.properties[table])
            const currFields = new Map(currFieldEntries)
            const nextFieldNames = new Set(fields.map(([n]) => n))
            const indexStmts = await indexStatements(query, table, fields, currFieldEntries, { patch })
            stmts.push(...indexStmts.before)
            for (const [name, prop] of fields) {
                const isRequired = required.has(name)
                const currProp = currFields.get(name)
                if (!currProp) {
                    stmts.push(`ALTER TABLE ${tableId} ADD COLUMN ${toFieldDef(name, prop, { required: isRequired })};`)
                    if (prop['$comment']) stmts.push(commentStmt(table, name, prop['$comment']))
                    continue
                }
                const propWithDefault = preserveDefault(prop, currProp)
                const changed = fieldChanged(diffs, table, name, prop) || isRequired !== currRequired.has(name) || propWithDefault['$comment'] !== currProp['$comment']
                if (changed) stmts.push(...alterFieldStmts(table, name, propWithDefault, currProp, isRequired, currRequired.has(name), changed))
            }
            if (!patch) {
                for (const name of currFields.keys()) {
                    if (!nextFieldNames.has(name))
                        stmts.push(`ALTER TABLE ${tableId} DROP COLUMN ${quoteId(name)};`)
                }
            }
            stmts.push(...indexStmts.after)
        }
    }

    if (!patch) {
        for (const table of currTables) {
            if (!nextTables.includes(table)) stmts.push(`DROP TABLE ${quoteId(table)};`)
        }
    }

    for (const stmt of stmts) {
        console.log(stmt)
        await query(stmt)
    }
    return { diffs, executed: stmts }
}

async function indexStatements(query, table, nextFields, currFields, { patch = false } = {}) {
    const before = [], after = [], tableId = quoteId(table)
    const indexes = await tableIndexes(query, table)
    const currPrimary = new Set(indexes.primary.length ? indexes.primary : primaryFields(currFields))
    const nextPrimary = new Set(primaryFields(nextFields))
    const primaryChanged = !setEqual(currPrimary, nextPrimary) && (!patch || nextPrimary.size)

    if (primaryChanged) {
        if (currPrimary.size) before.push(`ALTER TABLE ${tableId} DROP CONSTRAINT ${quoteId(indexes.primaryName ?? `${table}_pkey`)};`)
        if (nextPrimary.size) after.push(`ALTER TABLE ${tableId} ADD PRIMARY KEY (${[...nextPrimary].map(quoteId).join(', ')});`)
    }

    for (const [name, prop] of nextFields) {
        if (nextPrimary.has(name)) continue
        const nextKind = secondaryIndexKind(table, name, prop)
        const curr = indexes.secondary.find(i => i.column === name)
        const currKind = curr ? curr.unique ? 'UNIQUE INDEX' : 'INDEX' : null
        const changed = curr && currKind !== nextKind
        if (patch && !nextKind) continue
        if (changed) before.push(`DROP INDEX ${quoteId(curr.key)};`)
        if (nextKind && (!curr || changed)) after.push(createIndex(table, name, nextKind))
    }

    if (!patch) {
        for (const curr of indexes.secondary) {
            const wanted = nextFields.find(([name, prop]) => name === curr.column && secondaryIndexKind(table, name, prop))
            if (!wanted) before.push(`DROP INDEX ${quoteId(curr.key)};`)
        }
    }

    return { before, after }
}
