// pg/to-field.js - JSON Schema property -> PostgreSQL column definition
import { schemaType } from '../shared/sql.js'

const formats = { date: 'DATE', time: 'TIME', 'date-time': 'TIMESTAMP' }

export function quoteId(name) {
    return `"${String(name).replaceAll('"', '""')}"`
}

export function quoteLit(value) {
    return `'${String(value).replace(/'/g, "''")}'`
}

export function typeSql(prop) {
    const t = schemaType(prop)
    if (t === 'boolean') return 'BOOLEAN'
    if (t === 'integer') return integerType(prop)
    if (t === 'number') return prop.multipleOf ? 'NUMERIC' : 'DOUBLE PRECISION'
    if (t === 'object' || t === 'array') return 'JSONB'
    if (prop.format in formats) return formats[prop.format]
    if (prop.contentEncoding === 'base64') return 'BYTEA'
    return prop.maxLength ? `VARCHAR(${prop.maxLength})` : 'TEXT'
}

export function defaultLiteral(prop) {
    const t = schemaType(prop)
    if (t === 'boolean') return prop.default ? 'TRUE' : 'FALSE'
    if (t === 'integer' || t === 'number') return Number(prop.default)
    if (typeof prop.default === 'boolean') return "''"
    if (t === 'object' || t === 'array') return `${quoteLit(JSON.stringify(prop.default))}::jsonb`
    return quoteLit(prop.default)
}

export function toFieldDef(name, prop, { required = false } = {}) {
    const types = Array.isArray(prop.type) ? prop.type : [prop.type]
    const nullable = !required || types.includes('null')
    let sql = `${quoteId(name)} ${typeSql(prop)}`
    if (prop['x-autoincrement']) sql += ' GENERATED BY DEFAULT AS IDENTITY'
    sql += !nullable || prop['x-autoincrement'] ? ' NOT NULL' : ' NULL'
    if (prop.default != null && !prop['x-autoincrement']) sql += ` DEFAULT ${defaultLiteral(prop)}`
    return sql
}

function integerType(prop) {
    if (prop['x-autoincrement']) return 'INTEGER'
    if (prop.minimum == null && prop.maximum == null) return 'INTEGER'
    const min = prop.minimum ?? -Infinity, max = prop.maximum ?? Infinity
    if (min >= -32768 && max <= 32767) return 'SMALLINT'
    if (min >= -2147483648 && max <= 2147483647) return 'INTEGER'
    return 'BIGINT'
}
