import { assertFalse, assertStringIncludes } from 'https://deno.land/std@0.177.0/testing/asserts.ts';
import { schemaToDb } from '../to-db.js';

async function ddl(props, required = []) {
    const seen = [];
    const schema = { properties: { t: { additionalProperties: { properties: props, required } } } };
    await schemaToDb(schema, (sql) => { seen.push(sql); return Promise.resolve({ rows: [] }); }, { patch: true });
    return seen.join('\n');
}

Deno.test('pg schemaToDb: identity primary key', async () => {
    const sql = await ddl({ id: { type: 'integer', 'x-index': 'primary', 'x-autoincrement': true } }, ['id']);
    assertStringIncludes(sql, '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    assertStringIncludes(sql, 'PRIMARY KEY ("id")');
});

Deno.test('pg schemaToDb: composite primary key in one constraint', async () => {
    const sql = await ddl({
        a: { type: 'integer', 'x-index': 'primary' },
        b: { type: 'integer', 'x-index': 'primary' },
    });
    assertStringIncludes(sql, 'PRIMARY KEY ("a", "b")');
});

Deno.test('pg schemaToDb: secondary indexes are emitted after table creation', async () => {
    const sql = await ddl({
        id:   { type: 'integer', 'x-index': 'primary' },
        name: { type: 'string', maxLength: 100, 'x-index': 'unique' },
    });
    assertStringIncludes(sql, 'CREATE UNIQUE INDEX "idx_t_name" ON "t" ("name");');
});

Deno.test('pg schemaToDb: recreates changed secondary index', async () => {
    const seen = [];
    const schema = {
        properties: {
            t: {
                additionalProperties: {
                    properties: {
                        id:   { type: 'integer', 'x-index': 'primary' },
                        name: { type: 'string', maxLength: 100, 'x-index': 'unique' },
                    },
                },
            },
        },
    };
    await schemaToDb(schema, (sql) => {
        seen.push(sql);
        if (sql.includes('information_schema.tables')) return { rows: [{ table_name: 't' }] };
        if (sql.includes('information_schema.columns')) return { rows: [
            { column_name: 'id', udt_name: 'int4', is_nullable: 'NO', is_primary: true },
            { column_name: 'name', udt_name: 'varchar', character_maximum_length: 100, is_nullable: 'YES', is_index: true },
        ] };
        if (sql.includes('FROM pg_constraint')) return { rows: [{ conname: 't_pkey', columns: ['id'] }] };
        if (sql.includes('FROM pg_index i')) return { rows: [{ key: 'idx_t_name', column: 'name', unique: false }] };
        return { rows: [] };
    }, { patch: true });

    const sql = seen.join('\n');
    assertStringIncludes(sql, 'DROP INDEX "idx_t_name";');
    assertStringIncludes(sql, 'CREATE UNIQUE INDEX "idx_t_name" ON "t" ("name");');
});

Deno.test('pg schemaToDb: does not drop guessed primary constraint name', async () => {
    const seen = [];
    const schema = {
        properties: {
            t: {
                additionalProperties: {
                    properties: {
                        id: { type: 'integer', 'x-index': 'primary' },
                    },
                },
            },
        },
    };
    await schemaToDb(schema, (sql) => {
        seen.push(sql);
        if (sql.includes('information_schema.tables')) return { rows: [{ table_name: 't' }] };
        if (sql.includes('information_schema.columns')) return { rows: [
            { column_name: 'id', udt_name: 'int4', is_nullable: 'NO' },
        ] };
        return { rows: [] };
    }, { patch: true });

    const sql = seen.join('\n');
    assertFalse(sql.includes('DROP CONSTRAINT "t_pkey"'));
    assertStringIncludes(sql, 'ADD PRIMARY KEY ("id");');
});
