import { assertEquals } from 'https://deno.land/std@0.177.0/testing/asserts.ts';
import { toFieldDef } from '../to-field.js';

Deno.test('pg toFieldDef: type mapping', () => {
    assertEquals(toFieldDef('f', { type: 'boolean' }), '"f" BOOLEAN NULL');
    assertEquals(toFieldDef('f', { type: 'number' }),  '"f" DOUBLE PRECISION NULL');
    assertEquals(toFieldDef('f', { type: 'string', maxLength: 10 }), '"f" VARCHAR(10) NULL');
});

Deno.test('pg toFieldDef: required -> NOT NULL', () => {
    assertEquals(toFieldDef('f', { type: 'boolean' }, { required: true }), '"f" BOOLEAN NOT NULL');
});

Deno.test('pg toFieldDef: integer primary key identity', () => {
    assertEquals(
        toFieldDef('id', { type: 'integer', 'x-index': 'primary', 'x-autoincrement': true }),
        '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL',
    );
});

Deno.test('pg toFieldDef: boolean default uses PG boolean literal', () => {
    assertEquals(toFieldDef('f', { type: 'boolean', default: false }), '"f" BOOLEAN NULL DEFAULT FALSE');
});
