const schema = {
    properties: {
        account: {
            additionalProperties: { properties: {
                    id:        { 'x-index': 'primary', 'x-autoincrement': true, title:'id' },
                    number:    { type: 'string', 'x-index': 'unique', title: 'Kontonummer' },
                    name:      { type: 'string', title: 'Bezeichnung' },
                    type:      { type: 'string', enum: ['asset','liability','equity','revenue','expense'], title: 'Typ' },
                    category:  { type: 'string', title: 'Kategorie' },
                    currency:  { type: 'string', default: 'CHF', title: 'Währung', 'x-dataref': '../../../currency/$' },
                    is_active: { type: 'boolean', default: true, title: 'Aktiv' },
                    parent_id: { 'x-index': true, 'x-dataref': '../../../account/$', title: 'Übergeordnet' },
                },
                'x-display': 'number',
            },
            title: 'Kontenplan',
        },
        cost_center: {
            additionalProperties: { properties: {
                    id:        { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                    number:    { type: 'string', 'x-index': 'unique', title: 'Kostenstelle' },
                    name:      { type: 'string', title: 'Bezeichnung' },
                    parent_id: { 'x-index': true, 'x-dataref': '../../../cost_center/$', title: 'Übergeordnet' },
                },
                'x-display': 'name',
            },
            title: 'Kostenstelle',
        },
        tax_rate: {
            additionalProperties: { properties: {
                    id:         { 'x-index': 'primary', 'x-autoincrement': true },
                    name:       { type: 'string', title: 'Name' },
                    rate:       { type: 'number', title: 'Satz %' },
                    account_id: { 'x-dataref': '../../../account/$', title: 'Steuerkonto' },
                    valid_from: { type: 'string', format: 'date', title: 'Gültig ab' },
                    valid_to:   { type: 'string', format: 'date', title: 'Gültig bis' },
                },
                'x-display': 'name',
            },
            title: 'MWST-Satz',
        },
        currency: {
            additionalProperties: { properties: {
                    code:           { 'x-index': 'primary', type: 'string', 'x-transform': { case: 'upper' }, title: 'ISO Code' },
                    name:           { type: 'string', title: 'Name' },
                    symbol:         { type: 'string', title: 'Symbol' },
                    decimal_places: { type: 'integer', default: 2, title: 'Dezimalstellen' },
                },
                'x-display': 'code',
            },
            title: 'Währung',
        },
        fiscal_year: {
            additionalProperties: { properties: {
                    id:         { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                    name:       { type: 'string', title: 'Bezeichnung' },
                    start_date: { type: 'string', format: 'date', title: 'Start' },
                    end_date:   { type: 'string', format: 'date', title: 'Ende' },
                    is_closed:  { type: 'boolean', default: false, title: 'Geschlossen' },
                },
                'x-display': 'name',
            },
            title: 'Geschäftsjahr',
        },
        contact: {
            additionalProperties: { properties: {
                    id:           { 'x-index': 'primary', 'x-autoincrement': true },
                    type:         { type: 'string', enum: ['customer','vendor','both'] },
                    name:         { type: 'string', 'x-index': true, title: 'Name', 'x-transform': { case: 'upper' }, minLength: 2, maxLength: 10 },
                    is_company:   { type: 'boolean', default: false, title: 'Unternehmen' },
                    uid:          { type: 'string', title: 'UID' },
                    street:       { type: 'string', title: 'Strasse' },
                    zip:          { type: 'string', title: 'PLZ' },
                    city:         { type: 'string', title: 'Ort' },
                    country:      { type: 'string', default: 'CH', title: 'Land' },
                    email:        { type: 'string', format: 'email', 'x-index': true, title: 'E-Mail' },
                    phone:        { type: 'string', title: 'Telefon' },
                    iban:         { type: 'string', title: 'IBAN' },
                    currency:     { type: 'string', default: 'CHF', 'x-dataref': '../../../currency/$', title: 'Währung' },
                    payment_days: { type: 'integer', default: 30, title: 'Zahlungsziel' },
                    account_id:   { 'x-dataref': '../../../account/$', title: 'Konto' },
                    notes:        { type: 'string', 'x-multiline': true, title: 'Notizen' },
                },
                'x-display': 'name',
            },
            title: 'Kontakt',
        },
        journal: {
            additionalProperties: { properties: {
                    id:             { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                    name:           { type: 'string', title: 'Name' },
                    type:           { type: 'string', enum: ['general','sales','purchase','bank','cash'], title: 'Typ' },
                    fiscal_year_id: { 'x-index': true, 'x-dataref': '../../../fiscal_year/$', title: 'Geschäftsjahr' },
                },
                'x-display': 'name',
            },
            title: 'Journal',
        },
        entry: {
            additionalProperties: { properties: {
                    id:            { 'x-index': 'primary', 'x-autoincrement': true },
                    date:          { type: 'string', format: 'date', 'x-index': true, title: 'Datum', description: 'Buchungsdatum' },
                    reference:     { type: 'string', 'x-index': true, title: 'Belegnr.', description: 'Belegnummer', examples: ['INV-001', 'PAY-001'] },
                    description:   { type: 'string', title: 'Bezeichnung', description: 'Beschreibung des Belegs' },
                    journal_id:    { 'x-index': true, 'x-dataref': '../../../journal/$', title: 'Journal' }, 
                    contact_id:    { 'x-index': true, 'x-dataref': '../../../contact/$', title: 'Kontakt', description: 'Kunde/Supplier' },
                    currency:      { type: 'string', default: 'CHF', 'x-dataref': '../../../currency/$', title: 'Währung' },
                    exchange_rate: { type: 'number', default: 1, title: 'Kurs' },
                    is_posted:     { type: 'boolean', default: false, title: 'Gebucht' },
                    source:        { type: 'string', enum: ['manual','invoice','payment','import'], title: 'Quelle' },
                    created_by:    { 'x-dataref': '../../../user/$', title: 'Erstellt von' },
                    created_at:    { type: 'string', format: 'date-time', title: 'Erstellt am' },
                },
                'x-display': 'reference',
            },
            title: 'Journal',
        },
        entry_line: {
            additionalProperties: { properties: {
                    id:             { 'x-index': 'primary', 'x-autoincrement': true },
                    entry_id:       { 'x-index': true, 'x-dataref': '../../../entry/$', title: 'Buchungssatz' },
                    account_id:     { 'x-index': true, 'x-dataref': '../../../account/$', title: 'Konto' },
                    cost_center_id: { 'x-index': true, 'x-dataref': '../../../cost_center/$', title: 'Kostenstelle' },
                    debit:          { type: 'number', default: 0, title: 'Soll' },
                    credit:         { type: 'number', default: 0, title: 'Haben' },
                    tax_rate_id:    { 'x-dataref': '../../../tax_rate/$', title: 'MWST' },
                    tax_amount:     { type: 'number', default: 0, title: 'MWST-Betrag' },
                    description:    { type: 'string', title: 'Bezeichnung' },
                    reconciled:     { type: 'boolean', default: false, title: 'Abgeglichen' },
                },
                'x-display': 'id',
            },
            title: 'Buchungszeilen',
        },
        invoice: {
            additionalProperties: { properties: {
                    id:          { 'x-index': 'primary', 'x-autoincrement': true },
                    type:        { type: 'string', enum: ['outgoing','incoming'], title: 'Typ' },
                    number:      { type: 'string', 'x-index': 'unique', title: 'Nummer' },
                    contact_id:  { 'x-index': true, 'x-dataref': '../../../contact/$', title: 'Kontakt' },
                    date:        { type: 'string', format: 'date', title: 'Datum' },
                    due_date:    { type: 'string', format: 'date', title: 'Fälligkeit' },
                    currency:    { type: 'string', default: 'CHF', 'x-dataref': '../../../currency/$', title: 'Währung' },
                    status:      { type: 'string', enum: ['draft','sent','partial','paid','overdue','cancelled'], default: 'draft', title: 'Status' },
                    entry_id:    { 'x-dataref': '../../../entry/$', title: 'Buchung' },
                    notes:       { type: 'string', 'x-multiline': true, title: 'Notizen' },
                    total_net:   { type: 'number', title: 'Netto' },
                    total_tax:   { type: 'number', title: 'MWST' },
                    total_gross: { type: 'number', title: 'Brutto' },
                },
                'x-display': 'number',
            },
            title: 'Rechnungen',
        },
        invoice_line: {
            additionalProperties: { properties: {
                    id:           { 'x-index': 'primary', 'x-autoincrement': true },
                    invoice_id:   { 'x-index': true, 'x-dataref': '../../../invoice/$', title: 'Rechnung' },
                    product_id:   { 'x-index': true, 'x-dataref': '../../../product/$', title: 'Artikel' },
                    description:  { type: 'string', title: 'Bezeichnung' },
                    quantity:     { type: 'number', title: 'Menge' },
                    unit:         { type: 'string', title: 'Einheit' },
                    unit_price:   { type: 'number', title: 'Einzelpreis' },
                    discount_pct: { type: 'number', default: 0, title: 'Rabatt %' },
                    account_id:   { 'x-dataref': '../../../account/$', title: 'Erlöskonto' },
                    tax_rate_id:  { 'x-dataref': '../../../tax_rate/$', title: 'MWST' },
                    total_net:    { type: 'number', title: 'Total Netto' },
                },
            },
            title: 'Rechnungszeilen',
        },
        product: {
            additionalProperties: { properties: {
                    id:          { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                    sku:         { type: 'string', 'x-index': 'unique', title: 'Artikelnummer' },
                    name:        { type: 'string', title: 'Bezeichnung' },
                    unit:        { type: 'string', default: 'Stk.', title: 'Einheit' },
                    price:       { type: 'number', title: 'Preis' },
                    account_id:  { 'x-dataref': '../../../account/$', title: 'Erlöskonto' },
                    tax_rate_id: { 'x-dataref': '../../../tax_rate/$', title: 'MWST' },
                    is_active:   { type: 'boolean', default: true, title: 'Aktiv' },
                },
                'x-display': 'name',
            },
            title: 'Artikel',
        },
        payment: {
            additionalProperties: { properties: {
                id:         { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                date:       { type: 'string', format: 'date', title: 'Datum' },
                amount:     { type: 'number', title: 'Betrag' },
                currency:   { type: 'string', default: 'CHF', 'x-dataref': '../../../currency/$', title: 'Währung' },
                account_id: { 'x-dataref': '../../../account/$', title: 'Konto' },
                contact_id: { 'x-index': true, 'x-dataref': '../../../contact/$', title: 'Kontakt' },
                reference:  { type: 'string', title: 'ESR/QR-Ref' },
                entry_id:   { 'x-dataref': '../../../entry/$', title: 'Buchung' },
                method:     { type: 'string', enum: ['bank','cash','card','credit'], title: 'Zahlart' },
                notes:      { type: 'string', 'x-multiline': true, title: 'Notizen' },
            }},
            title: 'Zahlungen',
        },
        payment_invoice: {
            additionalProperties: { properties: {
                payment_id: { 'x-index': 'primary', 'x-dataref': '../../../payment/$', title: 'Zahlung' },
                invoice_id: { 'x-index': 'primary', 'x-dataref': '../../../invoice/$', title: 'Rechnung' },
                amount:     { type: 'number' },
            }},
            title: 'Zahlung–Rechnung',
        },
        bank_statement_line: {
            additionalProperties: { properties: {
                    id:               { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                    account_id:       { 'x-index': true, 'x-dataref': '../../../account/$', title: 'Konto' },
                    date:             { type: 'string', format: 'date' },
                    valuta:           { type: 'string', format: 'date' },
                    amount:           { type: 'number', title: 'Betrag' },
                    balance:          { type: 'number', title: 'Saldo' },
                    description:      { type: 'string', title: 'Betreff' },
                    reference:        { type: 'string', title: 'Verwendungszweck' },
                    matched_entry_id: { 'x-dataref': '../../../entry/$', title: 'Buchung' },
                    is_reconciled:    { type: 'boolean', default: false, title: 'Abgeglichen' },
                },
                'x-display': 'id',
            },
            title: 'Kontoauszug',
        },
        user: {
            additionalProperties: { properties: {
                    id:        { 'x-index': 'primary', 'x-autoincrement': true, title: 'ID' },
                    firstname: { type: 'string', title: 'Vorname' },
                    lastname:  { type: 'string', title: 'Nachname' },
                    email:     { type: 'string', format: 'email', 'x-index': 'unique', title: 'E-Mail' },
                    role:      { type: 'string', enum: ['admin','accountant','viewer'], title: 'Rolle' },
                    is_active: { type: 'boolean', default: true, title: 'Aktiv' },
                },
                'x-display': 'email',
            },
            title: 'Benutzer',
        },
    }
};

export default schema;